branches:
 only:
  - master

version: "0.0.1.{build}"

install:

  - curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/windows-download-cache-and-build-module-wheels.ps1 -O
  - ps: .\scripts\windows-download-cache.ps1
  - C:\Python35-x64\python.exe .\scripts\windows_build_module_wheels.py --py-envs 35-x64 36-x64


build: off

test: off

artifacts:

  # pushing entire folder as a zip archive
  - path: dist\*

deploy: off
